[workspace]
members = [
    "sign-service",
    "participant",
    "proto"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
dotenv = "0.15.0"
anyhow = "1.0.99"
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0.145"
serde = { version = "1.0.225", features = ["derive"] }
prost-types = "0.14.1"
tonic = "0.14.2"
prost = "0.14.1"
futures = "0.3.31"
thiserror = "2.0.16"
uniffi = "0.28.0"

[patch.crates-io]
gmp-mpfr-sys = { path = "vendor/gmp-mpfr-sys" }
